export function banderaDePaisImg(pais) {
  const codigo = obtenerCodigoISO(pais); // Necesitas esta función también
  if (!codigo) return pais;
  return `<img src="https://flagcdn.com/w40/${codigo}.png" alt="${pais}" title="${pais}" style="height:25px;">`;
}

function obtenerCodigoISO(pais) {
  const mapa = {
    albania: "al",
    alemania: "de",
    andorra: "ad",
    angola: "ao",
    arabia_saudi: "sa",
    arabia_saudita: "sa",
    argentina: "ar",
    argelia:"dz",
    australia: "au",
    austria: "at",
    belarus: "by",
    bielorrusia: "by",
    belgica: "be",
    birmania: "mm",
    bosnia_herzegovina: "ba",
    brasil: "br",
    brunei: "bn",
    bulgaria: "bg",
    burkina_faso: "bf",
    butan: "bt",
    camerun: "cm",
    cabo_verde:"cv",
    canada: "ca",
    chile: "cl",
    china: "cn",
    colombia: "co",
    corea_del_sur: "kr",
    costa_de_marfil: "ci",
    costa_rica: "cr",
    croacia: "hr",
    dinamarca: "dk",
    ecuador: "ec",
    egipto: "eg",
    el_salvador: "sv",
    emiratos_arabes_unidos: "ae",
    eslovaquia: "sk",
    eslovenia: "si",
    espana: "es",
    españa: "es",
    estonia: "ee",
    estados_unidos: "us",
    etiopia: "et",
    filipinas: "ph",
    finlandia: "fi",
    fiyi: "fj",
    francia: "fr",
    gabon: "ga",
    gambia: "gm",
    gales: "gb-wls",
    ghana: "gh",
    grecia: "gr",
    guadalupe: "gp",
    guatemala: "gt",
    guinea: "gn",
    guinea_bisau: "gw",
    guinea_ecuatorial: "gq",
    holanda: "nl",
    honduras: "hn",
    hungria: "hu",
    india: "in",
    indonesia: "id",
    inglaterra:"gb",
    irak: "iq",
    iran: "ir",
    irlanda: "ie",
    islandia: "is",
    israel: "il",
    italia: "it",
    japon: "jp",
    jordania: "jo",
    kazajistan: "kz",
    kenya: "ke",
    kirguistan: "kg",
    kiribati: "ki",
    kuwait: "kw",
    laos: "la",
    letonia: "lv",
    liechtenstein: "li",
    lituania: "lt",
    luxemburgo: "lu",
    macedonia: "mk",
    macedonia_del_norte:"mk",
    malasia: "my",
    malawi: "mw",
    mali: "ml",
    malta: "mt",
    marruecos: "ma",
    islas_marshall: "mh",
    mauritania: "mr",
    mexico: "mx",
    micronesia: "fm",
    moldavia: "md",
    monaco: "mc",
    mongolia: "mn",
    montenegro: "me",
    mozambique:"mz",
    myanmar: "mm",
    namibia: "na",
    nauru: "nr",
    nepal: "np",
    nicaragua: "ni",
    niger: "ne",
    nigeria: "ng",
    noruega: "no",
    nueva_zelanda: "nz",
    oman: "om",
    paises_bajos: "nl",
    pakistan: "pk",
    palau: "pw",
    panama: "pa",
    papua_nueva_guinea: "pg",
    paraguay: "py",
    peru: "pe",
    polonia: "pl",
    portugal: "pt",
    puerto_rico: "pr",
    qatar: "qa",
    rd_congo:"cd",
    rd_del_congo:"cd",
    republica_centroafricana:"cf",
    republica_checa: "cz",
    republica_dominicana: "do",
    rumania: "ro",
    rusia: "ru",
    samoa: "ws",
    san_marino: "sm",
    santa_lucia: "lc",
    senegal: "sn",
    serbia: "rs",
    singapur: "sg",
    siria: "sy",
    somalia: "so",
    sri_lanka: "lk",
    sudafrica: "za",
    suecia: "se",
    suiza: "ch",
    surinam: "sr",
    tailandia: "th",
    taiwan: "tw",
    tayikistan: "tj",
    tanzania: "tz",
    timor_leste: "tl",
    togo: "tg",
    tonga: "to",
    trinidad_y_tobago: "tt",
    tunez: "tn",
    turkmenistan: "tm",
    turquia: "tr",
    tuvalu: "tv",
    ucrania: "ua",
    uganda: "ug",
    uruguay: "uy",
    uzbekistan: "uz",
    vanuatu: "vu",
    vaticano: "va",
    venezuela: "ve",
    vietnam: "vn",
    yemen: "ye",
    zambia: "zm",
    zimbabue: "zw"
  };

  let key = pais.trim().toLowerCase()
    .replace(/á/g, "a")
    .replace(/é/g, "e")
    .replace(/í/g, "i")
    .replace(/ó/g, "o")
    .replace(/ú/g, "u")
    .replace(/ü/g, "u")
    .replace(/ñ/g, "n")
    .replace(/\s+/g, "_");

  return mapa[key];
}
